name: composite-workflow
on:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: "DevOps"
      - env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
        run: |
          echo "Random Number from Action: $RANDOM_NUMBER"
        shell: bash

